source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'SpiderImgur' do
  use_frameworks!
  
  pod 'AlamofireImage', '~> 3.5'
  pod 'OHHTTPStubs/Swift'
  
  target 'SpiderImgurTests' do
    inherit! :search_paths
  end
  
end
